#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: csi-unity
  labels:
    chart_group: dell-storage-charts
spec:
  releaseName: csi-unity
  chart:
    spec:
      chart: csi-unity
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: csi-unity-static-overrides
      valuesKey: csi-unity-static-overrides.yaml
    - kind: Secret
      name: csi-unity-system-overrides
      valuesKey: csi-unity-system-overrides.yaml
