#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

app.starlingx.io/component: platform

controller:
  image: dellemc/csm-application-mobility-controller:v0.3.0

licenseName: csm-application-mobility-license

objectstore:
  secretName: velero-cloud-credentials

veleroNamespace: dell-storage

velero:
  enabled: true
  app.starlingx.io/component: platform
  credentials:
    name: velero-cloud-credentials
  image:
    repository: velero/velero
    tag: v1.8.1
  initContainers:
  - name: dell-custom-velero-plugin
    image: dellemc/csm-application-mobility-velero-plugin:v0.3.0
    volumeMounts:
    - mountPath: /target
      name: plugins
  kubectl:
    image:
      repository: docker.io/bitnami/kubectl
      tag: latest
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

rbac:
  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
