[metadata]
name = k8sapp-dell-storage
summary = StarlingX sysinv extensions for app-dell-storage
long_description = file: README.rst
long_description_content_type = text/x-rst
license = Apache 2.0
author = StarlingX
author-email = starlingx-discuss@lists.starlingx.io
home-page = https://www.starlingx.io/
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 2
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5

[files]
packages =
    k8sapp_dell_storage

[global]
setup-hooks =
    pbr.hooks.setup_hook

[entry_points]
systemconfig.helm_applications =
    dell-storage = systemconfig.helm_plugins.dell_storage

systemconfig.helm_plugins.dell_storage =
    001_csi-powerstore = k8sapp_dell_storage.helm.csi_powerstore:CSIPowerStoreHelm
    002_csi-unity = k8sapp_dell_storage.helm.csi_unity:CSIUnityHelm
    003_csm-replication = k8sapp_dell_storage.helm.csm_replication:CSMReplicationHelm
    004_csm-observability = k8sapp_dell_storage.helm.csm_observability:CSMObservabilityHelm
    005_csm-application-mobility = k8sapp_dell_storage.helm.csm_application_mobility:CSMApplicationMobilityHelm
    006_csi-powerscale = k8sapp_dell_storage.helm.csi_powerscale:CSIPowerScaleHelm
    007_csi-powerflex = k8sapp_dell_storage.helm.csi_powerflex:CSIPowerFlexHelm
    008_csi-powermax = k8sapp_dell_storage.helm.csi_powermax:CSIPowerMaxHelm

systemconfig.fluxcd.kustomize_ops =
    dell-storage = k8sapp_dell_storage.kustomize.kustomize_dell_storage:DellStorageFluxCDKustomizeOperator

systemconfig.app_lifecycle =
    dell-storage = k8sapp_dell_storage.lifecycle.lifecycle_dell_storage:DellStorageAppLifecycleOperator

[wheel]
universal = 1
