#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: csm-replication
  labels:
    chart_group: dell-storage-charts
spec:
  releaseName: csm-replication
  chart:
    spec:
      chart: csm-replication
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: csm-replication-static-overrides
      valuesKey: csm-replication-static-overrides.yaml
    - kind: Secret
      name: csm-replication-system-overrides
      valuesKey: csm-replication-system-overrides.yaml
