#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: dell-storage
resources:
  - helmrelease.yaml
secretGenerator:
  - name: csi-powerstore-static-overrides
    files:
      - csi-powerstore-static-overrides.yaml
  - name: csi-powerstore-system-overrides
    files:
      - csi-powerstore-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
